 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: miapp
 spec:
   replicas: 2
   template:
     metadata:
       labels:
         app: web
     spec:
       containers:
         - name: front-end
           image: us.icr.io/test-borrar/miapp:v1
